version: '3.7'

x-base: &base
  restart: "on-failure"
  logging:
    options:
      max-size: "1m"
      max-file: "1"


services:
  sipn-reanalysis-plots:
    <<: *base
    image: "nsidc/sipn-reanalysis-plots:${SIPN_REANALYSIS_PLOTS_VERSION:-version_not_set}"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "FLASK_SECRET_KEY"
    volumes:
      - "${DATA_DIR}:/data:ro"
