name: sipn-reanalysis-plots
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.10.6

  # Dev dependencies:
  - bump2version ~=1.0
  - invoke ~=1.7
  - black ~=22.3.0
  - isort ~=5.10
  - pytest ~=7.1
  - mypy ~=0.942
  - shellcheck ~=0.8.0
  - typing-extensions ~=4.4

  - flake8 ~=4.0
  - flake8-bugbear ~=22.3.23
  - flake8-comprehensions ~=3.8
  - flake8-docstrings ~=1.6
  - flake8-use-fstring ~=1.3

  # Runtime dependencies:
  - flask ~=2.2
  - flask-wtf ~=1.0
  - loguru ~=0.6.0

  ## Data
  - xarray ~=2022.11
  - rioxarray ~=0.13.0
  - netcdf4 ~=1.6
  - numpy ~=1.23

  ## Plotting
  - cartopy ~=0.21.0

  # Implicit dependencies:
  - dask ~=2022.11  # Required for `xarray.open_mfdataset()`

  # Packages not on anaconda.org
  - pip:
    - bootstrap-flask ~=2.1
